### ISSUE TITLE
java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier

### ISSUE THREAD

**Issue by MrXlebNick** [PaymentHighway/paymenthighway-java-lib#46]
When I create `new PaymentAPI(serviceUrl, signatureKeyId, signatureSecret, account, merchant)`, it throws

```
java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:146)
        at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:958)
        at io.paymenthighway.connect.PaymentAPIConnection.defaultHttpClient(PaymentAPIConnection.java:55)
        at io.paymenthighway.PaymentAPI.<init>(PaymentAPI.java:36)
```

Android, declaring dependency as 
    `implementation 'io.paymenthighway:paymenthighway:1.10.1'`

What have I tried:
Adding dependency `implementation 'org.apache.httpcomponents:httpclient-android:4.3.5.1'`
It runs, but when I create `new PaymentAPI(serviceUrl, signatureKeyId, signatureSecret, account, merchant)`, it throws
```
java.lang.NoSuchMethodError: No virtual method setSSLContext(Ljavax/net/ssl/SSLContext;)Lorg/apache/http/impl/client/HttpClientBuilder; in class Lorg/apache/http/impl/client/HttpClientBuilder; or its super classes (declaration of 'org.apache.http.impl.client.HttpClientBuilder' appears in /data/app/my.app-zo5BdBtKOfd5zFhw6THnKQ==/base.apk)
        at io.paymenthighway.connect.PaymentAPIConnection.defaultHttpClient(PaymentAPIConnection.java:55)
        at io.paymenthighway.PaymentAPI.<init>(PaymentAPI.java:36)
```

**Comment by Swie** [comment]
Hello, this is a backend library and should not be used in-app, as the API keys can't be protected there. Is this what you're doing or did I misunderstand something?

An android application should communicate with your backend, which implements the Payment API calls to Payment Highway. In order to render our forms, your app should open a WebView to your backend URL, which then POSTs or redirects (GET) to Payment Highway.

In the backend you can use for example the dependency org.apache.httpcomponents.httpclient (version 4.5.5 or above). You can find some examples at https://github.com/PaymentHighway/paymenthighway-java-example-spring/tree/master/complete

**Comment by MrXlebNick** [comment]
Hello, thank you for your quick reply.
So that means that no payment highway components should be placed in the app at all?

**Comment by Swie** [comment]
Yes, that's right!
